# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2c71c757c4e64c051329e3fc7111f72368abee292a968769dc1e03fb816372b2155e059e05ac03b7f0020f2a28f835f2451898f9de58ff2bc349773bb30774

test:
  secret_key_base: 785a69fc6ff4d348272e3ef28d18782076a0e5ec6cda46b24a6762e5df16da4f914b34697920cca142450d6e285cb27c1acb87266f6e66ce1fbf1d3ba207a6a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
